version: "3.8"

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dpl_cricket_api
    restart: unless-stopped
    ports:
      - "8019:8000"
    environment:
      MONGODB_URL: mongodb+srv://althaf-mongo:EwrCidJv4MUUgHpL@cluster0.n1h85qi.mongodb.net/dpl-cricket?retryWrites=true&w=majority&appName=Cluster0
      DATABASE_NAME: calcutta_cricket_league
      ALLOWED_ORIGINS: '["*"]'
    volumes:
      - uploads_data:/tmp/cvcl_uploads
    networks:
      - cricket_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: https://dpl.bitroxy.co/api
    container_name: dpl_cricket_frontend
    restart: unless-stopped
    ports:
      - "8020:80"
    depends_on:
      - api
    networks:
      - cricket_network

volumes:
  uploads_data:

networks:
  cricket_network:
    driver: bridge
